const endings = {
  archimedes:
    '敘拉古城破，阿基米德在沙地作圖時遇害；他的著作與方法跨越兩千多年',
  galileo:
    '伽利略晚年在軟禁中失明，仍完成《兩門新科學》；他的觀測改變了人類看天空的方式',
  newton:
    '牛頓晚年主持皇家學會與造幣局，1727 年逝世；他的《自然哲學的數學原理》重塑了科學',
  gauss:
    '高斯在哥廷根工作至晚年，1855 年逝世；數論、測量、天文與磁學都留下他的尺度',
  turing:
    '圖靈在戰後持續研究電腦、人工智慧與形態發生，1954 年離世；後世才逐步還他應有的名字',
}

function book({
  id,
  grade,
  half,
  mathematician,
  episode,
  setting,
  era,
  acts,
  insights,
  endingKey,
  legendNote = null,
  props,
}) {
  return {
    id,
    grade,
    half,
    gradeLabel: `${['', '', '', '', '', '', '', '七', '八', '九'][grade]}${half === 1 ? '上' : '下'}`,
    mathematician,
    mathematicianSpeaker: 'Mathematician',
    episode,
    setting,
    era,
    acts,
    insights,
    props,
    endingSummary: endings[endingKey],
    legendNote,
  }
}

export const SCRIPT_CATALOG = [
  // 阿基米德：七上已有手調黃金樣板，以下五本以研究主題拆分。
  book({
    id: 'g7h2-archimedes',
    grade: 7,
    half: 2,
    mathematician: '阿基米德',
    episode: '尼羅河低鳴：螺旋汲水器',
    setting: '埃及尼羅河畔的灌溉工地',
    era: '西元前 3 世紀',
    acts: ['勘查低窪田地', '重畫螺旋水道', '試轉第一支木筒', '頂住暴漲河水', '讓清水越過堤岸'],
    insights: [
      '旋轉的螺旋能把低處的水一格一格托向高處',
      '傾角、轉速與出水量必須彼此配合，機械才真正替人省力',
    ],
    props: ['木製螺旋', '泥堤', '水槽', '陶罐', '繩尺'],
    endingKey: 'archimedes',
    legendNote: '阿基米德螺旋的發明歸屬帶有傳統記載色彩，劇本以「改良與驗證」呈現。',
  }),
  book({
    id: 'g8h1-archimedes',
    grade: 8,
    half: 1,
    mathematician: '阿基米德',
    episode: '數不完的沙：宇宙也能被寫下',
    setting: '敘拉古海岸與《數沙者》工坊',
    era: '西元前 3 世紀',
    acts: ['抓住一把海沙', '建立巨大數的記號', '推算地球尺度', '把宇宙一層層放大', '寫下最後一個上界'],
    insights: [
      '再巨大的數也能靠規律與記號被清楚表達',
      '宇宙看似無邊，推理仍能替未知畫出可討論的邊界',
    ],
    props: ['沙粒', '莎草紙', '星盤', '圓規', '海岸標尺'],
    endingKey: 'archimedes',
  }),
  book({
    id: 'g8h2-archimedes',
    grade: 8,
    half: 2,
    mathematician: '阿基米德',
    episode: '海面上的白光：鏡陣與守城校準',
    setting: '敘拉古城牆與銅鏡工坊',
    era: '第二次布匿戰爭期間',
    acts: ['磨平第一面銅鏡', '校準鏡框角度', '排列多面反光鏡', '在煙與風裡重測', '把光集中到同一點'],
    insights: [
      '每一面鏡子的角度都不同，反射光卻能在同一處會合',
      '守城不是靠傳說中的神火，而是材料、幾何與反覆校準',
    ],
    props: ['拋光銅鏡', '木框', '日影盤', '城牆標線', '羅馬船影'],
    endingKey: 'archimedes',
    legendNote: '燃燒鏡焚船缺乏可靠證據；劇本聚焦可驗證的反射與校準，不宣稱焚船成功。',
  }),
  book({
    id: 'g9h1-archimedes',
    grade: 9,
    half: 1,
    mathematician: '阿基米德',
    episode: '圓周之間：逼近 π 的兩道邊界',
    setting: '敘拉古幾何工坊',
    era: '西元前 3 世紀',
    acts: ['從六邊形起步', '倍增內接多邊形', '追趕外切邊界', '算到九十六邊', '把 π 夾在兩個數之間'],
    insights: [
      '多邊形的邊數越多，輪廓就越貼近圓',
      '不知道精確答案時，仍能用上下界把真值牢牢夾住',
    ],
    props: ['圓規', '九十六邊形圖', '繩尺', '蠟板', '內外切線'],
    endingKey: 'archimedes',
  }),
  book({
    id: 'g9h2-archimedes',
    grade: 9,
    half: 2,
    mathematician: '阿基米德',
    episode: '球與圓柱：他最珍惜的比例',
    setting: '敘拉古立體模型工坊',
    era: '西元前 3 世紀',
    acts: ['削出木球', '套上同高圓柱', '切開截面比較', '平衡體積關係', '決定墓碑上的圖形'],
    insights: [
      '球的每一層截面都能和圓柱、圓錐的差互相對應',
      '球的體積與表面積，都藏在外接圓柱的二比三比例裡',
    ],
    props: ['木球', '空心圓柱', '圓錐', '薄切片', '天平'],
    endingKey: 'archimedes',
  }),

  book({
    id: 'g7h1-galileo',
    grade: 7,
    half: 1,
    mathematician: '伽利略',
    episode: '斜面上的時間：重物真的比較快嗎',
    setting: '比薩的石造講堂與斜面實驗室',
    era: '16 世紀末',
    acts: ['質疑課堂定論', '削出平直斜槽', '記下滾球時間', '比較不同重量', '把證據帶回講堂'],
    insights: ['重量不同的球，在相同條件下加速規律一致', '把落下放慢成斜面運動，快得看不清的規律就能被測量'],
    props: ['銅球', '斜槽', '水鐘', '石塔', '刻度板'],
    endingKey: 'galileo',
    legendNote: '比薩斜塔公開落球常被視為後世傳說；劇本以有文獻基礎的斜面實驗為主。',
  }),
  book({
    id: 'g7h2-galileo',
    grade: 7,
    half: 2,
    mathematician: '伽利略',
    episode: '吊燈的來回：脈搏與擺',
    setting: '比薩主教座堂與工坊',
    era: '約 1580 年代',
    acts: ['在風裡看見吊燈', '用脈搏估計週期', '改變擺幅', '製作等長擺', '讓時間穩定下來'],
    insights: ['小幅擺動時，來回時間主要由擺長決定', '重複測量與比較比例，能把身體感覺變成可驗證的時間'],
    props: ['教堂吊燈', '細繩', '鉛球', '脈搏記錄', '木架'],
    endingKey: 'galileo',
  }),
  book({
    id: 'g8h1-galileo',
    grade: 8,
    half: 1,
    mathematician: '伽利略',
    episode: '望遠鏡轉向木星',
    setting: '帕多瓦工坊與威尼斯屋頂',
    era: '1609 至 1610 年',
    acts: ['磨出兩片透鏡', '提高望遠鏡倍率', '記下木星旁的光點', '追蹤四夜位置', '承認它們在繞行'],
    insights: ['木星旁的光點按規律改變位置，它們不是固定星', '不是所有天體都繞地球，天空比舊模型更寬'],
    props: ['望遠鏡', '透鏡', '木星觀測表', '屋頂欄杆', '星圖'],
    endingKey: 'galileo',
  }),
  book({
    id: 'g8h2-galileo',
    grade: 8,
    half: 2,
    mathematician: '伽利略',
    episode: '砲彈畫出的拋物線',
    setting: '威尼斯軍械庫外的測試場',
    era: '17 世紀初',
    acts: ['校直砲口', '量水平與下落', '拆開兩個方向', '預測落點', '把軌跡畫成拋物線'],
    insights: ['拋射運動可拆成水平前進與垂直下落', '兩種簡單運動疊在一起，軌跡就成為拋物線'],
    props: ['木製發射槽', '石球', '測距繩', '沙地落點', '軌跡圖'],
    endingKey: 'galileo',
  }),
  book({
    id: 'g9h1-galileo',
    grade: 9,
    half: 1,
    mathematician: '伽利略',
    episode: '相位與陰影：金星不肯服從舊宇宙',
    setting: '佛羅倫斯觀測室與羅馬論辯前夜',
    era: '1610 年代',
    acts: ['追蹤金星缺口', '比較視直徑', '排除舊模型', '整理呈堂圖稿', '在沉默前說出證據'],
    insights: ['金星完整相位只有繞太陽運行才能自然解釋', '模型不是信念；能否同時解釋觀測，才是它站不站得住的理由'],
    props: ['望遠鏡', '金星相位圖', '蠟燭太陽', '軌道模型', '論辯手稿'],
    endingKey: 'galileo',
  }),
  book({
    id: 'g9h2-galileo',
    grade: 9,
    half: 2,
    mathematician: '伽利略',
    episode: '軟禁中的最後一本書',
    setting: '阿切特里別墅',
    era: '1630 年代',
    acts: ['藏起未完成手稿', '重建斜面數據', '口述運動證明', '避開審查送稿', '完成《兩門新科學》'],
    insights: ['速度、時間與距離的關係能被幾何證明串起來', '即使觀測者被困住，能被重做的證據仍會走出門外'],
    props: ['封存手稿', '斜面數據', '口述紙頁', '訪客暗袋', '失明後的模型'],
    endingKey: 'galileo',
  }),

  book({
    id: 'g7h1-newton',
    grade: 7,
    half: 1,
    mathematician: '牛頓',
    episode: '白光裂開的房間',
    setting: '伍爾索普莊園的暗室',
    era: '1660 年代',
    acts: ['封住窗縫', '讓光穿過三稜鏡', '標記色帶位置', '加入第二枚稜鏡', '讓顏色重新合成白光'],
    insights: ['顏色原本就藏在白光裡，不是玻璃把光染色', '能把現象拆開再重組的實驗，才足以推翻直覺'],
    props: ['三稜鏡', '窗板小孔', '白牆', '色帶刻度', '第二枚稜鏡'],
    endingKey: 'newton',
    legendNote: '蘋果故事僅作時代氛圍，不作本劇本的 Eureka 核心。',
  }),
  book({
    id: 'g7h2-newton',
    grade: 7,
    half: 2,
    mathematician: '牛頓',
    episode: '流動的量：變化也能計算',
    setting: '瘟疫期間的伍爾索普書房',
    era: '1665 至 1666 年',
    acts: ['追蹤移動點', '比較相鄰時刻', '縮短時間間隔', '畫出切線方向', '把流量寫成規則'],
    insights: ['位置持續改變時，極短時間內的變化能描述當下速度', '總量可以由無數微小變化累積回來'],
    props: ['流數草稿', '滴水計時器', '曲線蠟板', '切線尺', '羽毛筆'],
    endingKey: 'newton',
  }),
  book({
    id: 'g8h1-newton',
    grade: 8,
    half: 1,
    mathematician: '牛頓',
    episode: '月亮為什麼沒有掉下來',
    setting: '伍爾索普果園與劍橋書房',
    era: '1660 至 1680 年代',
    acts: ['比較落物與月球', '估算地球半徑', '換算月球距離', '檢查平方反比', '把天與地寫進同一條定律'],
    insights: ['月球一直在落，只是前進得夠快而不斷錯過地面', '地上的落下與天上的軌道，服從同一種引力'],
    props: ['月球軌道圖', '地球模型', '果園落物', '距離表', '平方反比草稿'],
    endingKey: 'newton',
  }),
  book({
    id: 'g8h2-newton',
    grade: 8,
    half: 2,
    mathematician: '牛頓',
    episode: '《原理》交稿前夜',
    setting: '劍橋書房與皇家學會印刷間',
    era: '1680 年代',
    acts: ['回覆哈雷的問題', '重建軌道證明', '校對運動三定律', '補上潮汐推論', '把《原理》送進印刷機'],
    insights: ['力不是維持運動所必需，而是改變運動狀態的原因', '作用與反作用成對出現，從碰撞到軌道都不例外'],
    props: ['《原理》手稿', '軌道圖', '印刷鉛字', '碰撞小車', '哈雷來信'],
    endingKey: 'newton',
  }),
  book({
    id: 'g9h1-newton',
    grade: 9,
    half: 1,
    mathematician: '牛頓',
    episode: '玻璃之間的彩色圓環',
    setting: '劍橋光學實驗室',
    era: '17 世紀末',
    acts: ['把曲面玻璃壓上平板', '量第一圈半徑', '追蹤明暗環', '改變玻璃間隙', '從圓環反推薄層厚度'],
    insights: ['兩片玻璃間極薄的空隙，會把光排成規律圓環', '看不見的厚度，可以從看得見的幾何圖樣反推'],
    props: ['凸透鏡', '平玻璃', '彩色圓環', '測微尺', '暗箱'],
    endingKey: 'newton',
  }),
  book({
    id: 'g9h2-newton',
    grade: 9,
    half: 2,
    mathematician: '牛頓',
    episode: '造幣局的假金幣',
    setting: '倫敦塔造幣局',
    era: '1690 年代',
    acts: ['封存可疑硬幣', '比較重量分布', '追查模具缺口', '重排證詞時間', '讓新鑄幣通過檢驗'],
    insights: ['單枚硬幣可能騙人，整批重量與尺寸的分布卻會留下痕跡', '證據必須能彼此驗證；數字、模具與證詞缺一不可'],
    props: ['銀幣', '精密天平', '模具', '熔爐紀錄', '證詞冊'],
    endingKey: 'newton',
  }),

  book({
    id: 'g7h1-gauss',
    grade: 7,
    half: 1,
    mathematician: '高斯',
    episode: '一百個數字沒有那麼長',
    setting: '布倫瑞克小學教室',
    era: '1780 年代',
    acts: ['接下老師的長題', '把頭尾配成一組', '確認每組總和', '處理奇偶項數', '在石板寫下 5050'],
    insights: ['從頭與尾配對，每組都有相同總和', '找出結構，比一項一項苦算更快也更可靠'],
    props: ['石板', '粉筆', '一百張數字卡', '長木桌', '老師的計時鐘'],
    endingKey: 'gauss',
  }),
  book({
    id: 'g7h2-gauss',
    grade: 7,
    half: 2,
    mathematician: '高斯',
    episode: '正十七邊形的清晨',
    setting: '哥廷根學生宿舍與幾何教室',
    era: '1796 年',
    acts: ['把圓分成十七份', '追查質數結構', '拆出可作圖長度', '只用直尺圓規落點', '畫出兩千年未見的新正多邊形'],
    insights: ['某些正多邊形能否尺規作出，藏在邊數的代數結構裡', '代數關係可以一步步變成紙上的幾何作圖'],
    props: ['圓規', '無刻度直尺', '十七等分圓', '作圖弧線', '計算草稿'],
    endingKey: 'gauss',
  }),
  book({
    id: 'g8h1-gauss',
    grade: 8,
    half: 1,
    mathematician: '高斯',
    episode: '消失在太陽光裡的穀神星',
    setting: '哥廷根書房與歐洲天文台通信網',
    era: '1801 年',
    acts: ['收齊零散觀測', '修正不同天文台誤差', '擬合最可能軌道', '預測重現位置', '在夜空找回穀神星'],
    insights: ['觀測都有誤差，最可靠的軌道要讓整體偏差最小', '數列與函數能從零散位置延伸出尚未看見的下一點'],
    props: ['穀神星觀測表', '星圖', '通信信件', '軌道尺', '望遠鏡'],
    endingKey: 'gauss',
  }),
  book({
    id: 'g8h2-gauss',
    grade: 8,
    half: 2,
    mathematician: '高斯',
    episode: '漢諾威的三角網',
    setting: '漢諾威山野與哥廷根測量站',
    era: '1820 年代',
    acts: ['在山頂架起測量儀', '建立第一個基準三角形', '越過河谷延伸三角網', '修正累積誤差', '把整片土地接成一張圖'],
    insights: ['只要一條基線與足夠角度，就能把距離難量的土地連成三角網', '每個小誤差都會傳遞，封閉圖形能逼它現形'],
    props: ['測量儀', '山頂信號鏡', '基線木樁', '三角網地圖', '誤差表'],
    endingKey: 'gauss',
  }),
  book({
    id: 'g9h1-gauss',
    grade: 9,
    half: 1,
    mathematician: '高斯',
    episode: '誤差長成一座鐘',
    setting: '哥廷根天文台的資料室',
    era: '19 世紀初',
    acts: ['攤開重複觀測', '找出誤差中心', '比較兩側分布', '畫出鐘形曲線', '替最可能數值劃定範圍'],
    insights: ['單次觀測會偏高或偏低，大量誤差卻常在中心附近形成對稱分布', '最可靠的估計不是挑一筆最順眼的數，而是讓整體偏差付出最小代價'],
    props: ['觀測誤差表', '盒狀分布圖', '鐘形曲線', '天文鐘', '估計草稿'],
    endingKey: 'gauss',
  }),
  book({
    id: 'g9h2-gauss',
    grade: 9,
    half: 2,
    mathematician: '高斯',
    episode: '地球磁場的無形地圖',
    setting: '哥廷根磁學觀測站',
    era: '1830 年代',
    acts: ['隔絕鐵器干擾', '校準磁針擺動', '同步各地觀測時間', '把方向強度畫上地圖', '確認磁場不是局部怪象'],
    insights: ['磁針偏轉能把看不見的磁場方向與強度變成數據', '跨地點同步測量，才能從局部讀數拼出地球尺度的圖'],
    props: ['磁力計', '無鐵觀測屋', '同步時鐘', '磁場地圖', '電報線'],
    endingKey: 'gauss',
  }),

  book({
    id: 'g7h1-turing',
    grade: 7,
    half: 1,
    mathematician: '艾倫・圖靈',
    episode: '少年圖靈：思考能拆成步驟嗎',
    setting: '英格蘭寄宿學校的空教室',
    era: '1920 年代',
    acts: ['把難題拆成指令', '替每一步編號', '沿紙帶左右移動', '找出會卡住的規則', '讓另一個人照步驟得到同答案'],
    insights: ['只要步驟明確，思考的一部分可以交給規則執行', '真正困難的不是算得快，而是說清楚每一步何時停止'],
    props: ['方格紙帶', '鉛筆', '規則卡', '狀態標記', '手搖計算器'],
    endingKey: 'turing',
  }),
  book({
    id: 'g7h2-turing',
    grade: 7,
    half: 2,
    mathematician: '艾倫・圖靈',
    episode: '無限紙帶上的機器',
    setting: '劍橋大學的深夜書房',
    era: '1936 年',
    acts: ['畫出無限方格', '定義讀寫規則', '加入狀態轉換', '測試會不會停機', '寫成〈論可計算數〉'],
    insights: ['有限規則配上一條可延伸紙帶，就能描述一般計算過程', '有些問題不是算得不夠久，而是不存在能保證判定的通用程序'],
    props: ['紙帶模型', '讀寫頭', '狀態表', '停機記號', '論文手稿'],
    endingKey: 'turing',
  }),
  book({
    id: 'g8h1-turing',
    grade: 8,
    half: 1,
    mathematician: '艾倫・圖靈',
    episode: 'Bletchley Park：讓不可能的工作縮小',
    setting: '布萊切利園分析小屋',
    era: '第二次世界大戰期間',
    acts: ['整理大量截收紀錄', '排除矛盾設定', '安排機器測試順序', '比較候選結果', '把一天的搜尋壓進幾小時'],
    insights: ['機器不用理解語句，也能高速排除不可能的候選', '人提出可檢驗的限制，機器負責重複搜索，兩者合作才有力量'],
    props: ['候選表', '轉輪示意模型', '排程板', '打孔紙', '值班紀錄'],
    endingKey: 'turing',
  }),
  book({
    id: 'g8h2-turing',
    grade: 8,
    half: 2,
    mathematician: '艾倫・圖靈',
    episode: '機器會不會思考',
    setting: '曼徹斯特大學電腦實驗室',
    era: '1950 年',
    acts: ['改寫太模糊的問題', '設計隔牆問答', '區分規則與表現', '處理反例與偏見', '完成〈計算機器與智能〉'],
    insights: ['與其爭論「思考」的定義，不如先設計能被觀察與質疑的測試', '模仿人的回答不等於擁有人的心，但會迫使我們重新界定智能'],
    props: ['電傳打字機', '隔牆問答紙', 'Manchester Mark I', '測試紀錄', '反例卡'],
    endingKey: 'turing',
  }),
  book({
    id: 'g9h1-turing',
    grade: 9,
    half: 1,
    mathematician: '艾倫・圖靈',
    episode: 'ACE：還沒被造出的電腦',
    setting: '英國國家物理實驗室',
    era: '1945 至 1947 年',
    acts: ['決定記憶體配置', '畫出指令流', '估算延遲線時間', '縮短資料路徑', '讓紙上 ACE 跑完第一段程序'],
    insights: ['程式與資料都能存進同一套記憶體，由指令依序改變機器狀態', '硬體速度不只看零件，資料走過的路徑與等待時間同樣關鍵'],
    props: ['ACE 設計圖', '延遲線記憶體', '指令卡', '訊號路徑', '時序表'],
    endingKey: 'turing',
  }),
  book({
    id: 'g9h2-turing',
    grade: 9,
    half: 2,
    mathematician: '艾倫・圖靈',
    episode: '斑點如何長出來',
    setting: '曼徹斯特的形態發生研究室',
    era: '1951 至 1952 年',
    acts: ['觀察葉片與獸紋', '寫下兩種化學物質', '讓它們擴散反應', '追蹤波紋失穩', '從方程式長出斑點'],
    insights: ['均勻系統也可能因反應與擴散速度不同，自發長出規律圖樣', '生命形狀不必預先畫好；簡單局部規則能在空間中放大成花紋'],
    props: ['反應皿', '濃度表', '擴散格網', '斑點照片', '方程式手稿'],
    endingKey: 'turing',
  }),
]

